# Generated by Django 3.1.7 on 2021-04-30 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mireplica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comentario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mireplica.comment'),
            preserve_default=False,
        ),
    ]
