# Generated by Django 3.1.7 on 2021-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mireplica', '0003_remove_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergrupo',
            name='lider',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
